# Generated by Django 2.2.3 on 2019-07-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourmoviedetail',
            name='Participating',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ourmoviedetail',
            name='actors',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ourmoviedetail',
            name='actors_img',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ourmoviedetail',
            name='actors_role',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ourmoviedetail',
            name='audiAcc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ourmoviedetail',
            name='dialog',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ourmoviedetail',
            name='genres',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ourmoviedetail',
            name='image_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ourmoviedetail',
            name='large_image',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ourmoviedetail',
            name='movieCd',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ourmoviedetail',
            name='nationNm',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ourmoviedetail',
            name='openDt',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ourmoviedetail',
            name='rating',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ourmoviedetail',
            name='score_reple_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ourmoviedetail',
            name='score_reple_like',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ourmoviedetail',
            name='score_reples',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ourmoviedetail',
            name='show1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ourmoviedetail',
            name='show2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ourmoviedetail',
            name='showTm',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ourmoviedetail',
            name='story',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ourmoviedetail',
            name='watchGradeNm',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
