# Generated by Django 2.1.5 on 2019-05-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieCd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieCd', models.TextField()),
                ('rank', models.TextField()),
                ('audiAcc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MovieDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieNm', models.CharField(max_length=100)),
                ('showTm', models.IntegerField()),
                ('openDt', models.DateTimeField()),
                ('nationNm', models.CharField(max_length=100)),
                ('genres', models.CharField(max_length=100)),
                ('directors', models.CharField(max_length=100)),
                ('actors', models.CharField(max_length=100)),
                ('watchGradeNm', models.CharField(max_length=100)),
            ],
        ),
    ]
