# Generated by Django 2.1.5 on 2019-05-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviecd_moviedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetail',
            name='openDt',
            field=models.DateField(),
        ),
    ]
