# Generated by Django 2.1.5 on 2019-05-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20190514_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedetail',
            name='dialog',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
