# Generated by Django 2.1.5 on 2019-05-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_moviedetail_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedetail',
            name='story',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
