# Generated by Django 2.1.5 on 2019-05-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_moviedetail_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedetail',
            name='Participating',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moviedetail',
            name='rating',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
