# Generated by Django 2.1.5 on 2019-05-15 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20190514_0830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviedetail',
            old_name='directors',
            new_name='actors_img',
        ),
    ]
