# Generated by Django 2.1.5 on 2019-05-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20190515_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedetail',
            name='score_reples',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
