# Generated by Django 2.1.5 on 2019-05-15 02:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0010_auto_20190515_0157'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurMovieCd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieCd', models.TextField()),
                ('rank', models.TextField()),
                ('audiAcc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OurMovieDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieNm', models.CharField(max_length=100)),
                ('showTm', models.IntegerField()),
                ('openDt', models.DateField()),
                ('nationNm', models.CharField(max_length=100)),
                ('genres', models.CharField(max_length=100)),
                ('actors', models.CharField(max_length=100)),
                ('actors_img', models.CharField(max_length=100)),
                ('watchGradeNm', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=100)),
                ('story', models.TextField()),
                ('rating', models.CharField(max_length=100)),
                ('Participating', models.CharField(max_length=100)),
                ('score_reples', models.TextField()),
                ('dialog', models.CharField(max_length=100)),
                ('movieCd', models.TextField()),
                ('rank', models.TextField()),
                ('audiAcc', models.TextField()),
                ('show1', models.CharField(max_length=100)),
                ('show2', models.CharField(max_length=100)),
                ('average', models.FloatField()),
                ('likes', models.ManyToManyField(blank=True, related_name='like_post_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='moviedetail',
            name='show1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moviedetail',
            name='show2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
