# Generated by Django 2.1.5 on 2019-05-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20190515_0453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedetail',
            name='actors_img',
        ),
        migrations.RemoveField(
            model_name='ourmoviedetail',
            name='rank',
        ),
        migrations.AlterField(
            model_name='ourmoviedetail',
            name='average',
            field=models.FloatField(null=True),
        ),
    ]
