# Generated by Django 2.1.5 on 2019-05-16 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_auto_20190515_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedetail',
            name='actors_img',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moviedetail',
            name='actors_role',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourmoviedetail',
            name='actors_role',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
