# Generated by Django 2.1.5 on 2019-05-16 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_auto_20190516_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedetail',
            name='large_image',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourmoviedetail',
            name='large_image',
            field=models.CharField(default=11, max_length=200),
            preserve_default=False,
        ),
    ]
