# Generated by Django 2.1.5 on 2019-05-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_auto_20190516_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedetail',
            name='score_reple_id',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moviedetail',
            name='score_reple_like',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourmoviedetail',
            name='score_reple_id',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourmoviedetail',
            name='score_reple_like',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
